[package]
name = "auxiliary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"

[dependencies.stm32f4]
version = "0.14.0"
features = ["stm32f469", "rt"]
